services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: portava
      POSTGRES_PASSWORD: portava
      POSTGRES_DB: portava
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  postgres_data:
