/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PortalsRouteImport } from './routes/portals'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalsIndexRouteImport } from './routes/portals.index'
import { Route as PortalsNewRouteImport } from './routes/portals.new'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalsRoute = PortalsRouteImport.update({
  id: '/portals',
  path: '/portals',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalsIndexRoute = PortalsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalsRoute,
} as any)
const PortalsNewRoute = PortalsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PortalsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/portals': typeof PortalsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/portals/new': typeof PortalsNewRoute
  '/portals/': typeof PortalsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/portals/new': typeof PortalsNewRoute
  '/portals': typeof PortalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/portals': typeof PortalsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/portals/new': typeof PortalsNewRoute
  '/portals/': typeof PortalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/portals' | '/settings' | '/portals/new' | '/portals/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/settings' | '/portals/new' | '/portals'
  id: '__root__' | '/' | '/portals' | '/settings' | '/portals/new' | '/portals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PortalsRoute: typeof PortalsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portals': {
      id: '/portals'
      path: '/portals'
      fullPath: '/portals'
      preLoaderRoute: typeof PortalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portals/': {
      id: '/portals/'
      path: '/'
      fullPath: '/portals/'
      preLoaderRoute: typeof PortalsIndexRouteImport
      parentRoute: typeof PortalsRoute
    }
    '/portals/new': {
      id: '/portals/new'
      path: '/new'
      fullPath: '/portals/new'
      preLoaderRoute: typeof PortalsNewRouteImport
      parentRoute: typeof PortalsRoute
    }
  }
}

interface PortalsRouteChildren {
  PortalsNewRoute: typeof PortalsNewRoute
  PortalsIndexRoute: typeof PortalsIndexRoute
}

const PortalsRouteChildren: PortalsRouteChildren = {
  PortalsNewRoute: PortalsNewRoute,
  PortalsIndexRoute: PortalsIndexRoute,
}

const PortalsRouteWithChildren =
  PortalsRoute._addFileChildren(PortalsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PortalsRoute: PortalsRouteWithChildren,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
